# Generated by Django 5.1.15 on 2026-04-19 23:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhishingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("url_features", models.JSONField(default=dict)),
                ("is_phishing_predicted", models.BooleanField()),
                (
                    "confidence",
                    models.FloatField(help_text="Model confidence in [0, 1]"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="phishing_events",
                        to="behavior.behaviorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="phishing_ph_session_e1661d_idx",
                    ),
                    models.Index(
                        fields=["is_phishing_predicted"],
                        name="phishing_ph_is_phis_5a7046_idx",
                    ),
                ],
            },
        ),
    ]
