# Generated by Django 5.1.15 on 2026-04-19 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("behavior", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("recipient_account", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("risk_score", models.FloatField(blank=True, null=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("challenge", "Challenge (2FA)"),
                            ("deny", "Deny"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_attempts",
                        to="behavior.behaviorsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("behavior_score", models.FloatField(blank=True, null=True)),
                ("phishing_score", models.FloatField(blank=True, null=True)),
                ("combined_score", models.FloatField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("allow", "Allow"),
                            ("challenge", "Challenge (2FA)"),
                            ("deny", "Deny"),
                            ("pending", "Pending"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("model_versions", models.JSONField(default=dict)),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="transactions.transactionattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transactionattempt",
            index=models.Index(
                fields=["user", "created_at"], name="transaction_user_id_650526_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transactionattempt",
            index=models.Index(
                fields=["decision"], name="transaction_decisio_ce2365_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["attempt", "created_at"], name="transaction_attempt_73cb9a_idx"
            ),
        ),
    ]
