# Generated by Django 5.1.15 on 2026-04-19 23:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("is_enrollment", models.BooleanField(default=False)),
                ("session_token", models.UUIDField(default=uuid.uuid4, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="KeystrokeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_category",
                    models.CharField(
                        choices=[
                            ("letter", "Letter"),
                            ("digit", "Digit"),
                            ("special", "Special"),
                            ("modifier", "Modifier"),
                        ],
                        max_length=16,
                    ),
                ),
                ("key_down_at", models.FloatField(help_text="ms from session start")),
                ("key_up_at", models.FloatField(help_text="ms from session start")),
                (
                    "dwell_time_ms",
                    models.FloatField(
                        editable=False,
                        help_text="key_up_at − key_down_at, stored for indexing",
                    ),
                ),
                (
                    "flight_time_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Gap between previous key_up and this key_down",
                        null=True,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keystrokes",
                        to="behavior.behaviorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["key_down_at"],
            },
        ),
        migrations.CreateModel(
            name="MouseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("move", "Move"),
                            ("click", "Click"),
                            ("scroll", "Scroll"),
                        ],
                        max_length=8,
                    ),
                ),
                ("timestamp_ms", models.FloatField(help_text="ms from session start")),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("button", models.CharField(blank=True, max_length=16, null=True)),
                ("delta_x", models.IntegerField(blank=True, null=True)),
                ("delta_y", models.IntegerField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouse_events",
                        to="behavior.behaviorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp_ms"],
            },
        ),
        migrations.AddIndex(
            model_name="behaviorsession",
            index=models.Index(
                fields=["user", "started_at"], name="behavior_be_user_id_f18731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorsession",
            index=models.Index(
                fields=["session_token"], name="behavior_be_session_86362c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keystrokeevent",
            index=models.Index(
                fields=["session", "key_down_at"], name="behavior_ke_session_5a120c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mouseevent",
            index=models.Index(
                fields=["session", "timestamp_ms"],
                name="behavior_mo_session_e5ed6d_idx",
            ),
        ),
    ]
