# Generated by Django 5.1.15 on 2026-04-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behavior", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="keystrokeevent",
            name="client_event_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="UUID assigned by the browser; used for idempotent ingestion",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="mouseevent",
            name="client_event_id",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="UUID assigned by the browser; used for idempotent ingestion",
                null=True,
                unique=True,
            ),
        ),
    ]
