# Generated by Django 5.1.15 on 2026-05-18 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_blob", models.BinaryField()),
                (
                    "feature_schema_version",
                    models.CharField(
                        help_text="Version of BehaviorFeatures dataclass schema. Bump when feature list changes.",
                        max_length=32,
                    ),
                ),
                (
                    "detector_version",
                    models.CharField(
                        help_text="Version of detector algorithm + hyperparameters. Bump when IsolationForest contamination or other params change.",
                        max_length=32,
                    ),
                ),
                ("trained_at", models.DateTimeField(auto_now=True)),
                (
                    "n_training_sessions",
                    models.IntegerField(
                        help_text="Number of enrollment sessions used for training"
                    ),
                ),
                (
                    "n_training_samples",
                    models.IntegerField(
                        help_text="Number of feature vectors (after per-repetition split)"
                    ),
                ),
                (
                    "training_score_mean",
                    models.FloatField(
                        help_text="Mean anomaly score on training data", null=True
                    ),
                ),
                (
                    "training_score_std",
                    models.FloatField(
                        help_text="Std anomaly score on training data", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="If False, detector falls back to suspicious. Useful for disabling stale models without deletion.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Behavior Profile",
                "verbose_name_plural": "Behavior Profiles",
            },
        ),
    ]
