# Generated by Django 5.1.15 on 2026-05-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ml_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("source_url", models.CharField(blank=True, max_length=255)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Evaluation Dataset",
                "verbose_name_plural": "Evaluation Datasets",
            },
        ),
        migrations.CreateModel(
            name="EvaluationSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_id", models.CharField(max_length=64)),
                (
                    "feature_vectors",
                    models.JSONField(
                        help_text="List of feature vectors as dicts matching BehaviorFeatures"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Source-specific data: n_sessions, n_repetitions, etc.",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="ml_engine.evaluationdataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluation Subject",
                "verbose_name_plural": "Evaluation Subjects",
                "ordering": ["dataset", "subject_id"],
                "unique_together": {("dataset", "subject_id")},
            },
        ),
    ]
